In [2]:
A=[]
for i in range(4):
    A.append([])
    for j in range(4):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))
        
for i in range(4):
    for j in range(4):
        print(A[i][j], end="  " if A[i][j]>=0 else " ")
    print("")


Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 2
Introduce el elemento (0,2): 3
Introduce el elemento (0,3): 4
Introduce el elemento (1,0): 0
Introduce el elemento (1,1): -1
Introduce el elemento (1,2): -2
Introduce el elemento (1,3): -3
Introduce el elemento (2,0): -4
Introduce el elemento (2,1): -5
Introduce el elemento (2,2): -6
Introduce el elemento (2,3): -7
Introduce el elemento (3,0): 0
Introduce el elemento (3,1): 1
Introduce el elemento (3,2): 2
Introduce el elemento (3,3): 3
1.0  2.0  3.0  4.0  
0.0  -1.0 -2.0 -3.0 
-4.0 -5.0 -6.0 -7.0 
0.0  1.0  2.0  3.0  


In [3]:
n = int(input("número de filas: "))
m = int(input("número de columnas: "))
A=[]
print("\n Matriz A \n")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}) de la matriz A: ".format(i,j))))
        
B=[]
print("\n Matriz B \n")
for i in range(n):
    B.append([])
    for j in range(m):
        B[i].append(float(input("Introduce el elemento ({},{}) de la matriz B: ".format(i,j))))

C=[]
for i in range(n):
    C.append([])
    for j in range(m):
        C[i].append(A[i][j]+B[i][j])
        
print("\n Matriz A + B: ")
for i in range(n):
    for j in range(m):
        print(C[i][j], end=" ")
    print("")


número de filas: 2
número de columnas: 2

 Matriz A 

Introduce el elemento (0,0) de la matriz A: 1
Introduce el elemento (0,1) de la matriz A: 2
Introduce el elemento (1,0) de la matriz A: 3
Introduce el elemento (1,1) de la matriz A: 4

 Matriz B 

Introduce el elemento (0,0) de la matriz B: 4
Introduce el elemento (0,1) de la matriz B: 5
Introduce el elemento (1,0) de la matriz B: 6
Introduce el elemento (1,1) de la matriz B: 7

 Matriz A + B: 
5.0 7.0 
9.0 11.0 


In [10]:
n = int(input("número de filas de A: "))
m = int(input("número de columnas de A: "))
p = int(input("número de columnas de B: "))

A=[]
print("\n Matriz A \n")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}) de la matriz A: ".format(i,j))))
        
B=[]
print("\n Matriz B \n")
for i in range(m):
    B.append([])
    for j in range(p):
        B[i].append(float(input("Introduce el elemento ({},{}) de la matriz B: ".format(i,j))))

C=[]
for i in range(n):
    C.append([])
    for j in range(p):
        elemento = 0
        for k in range(m):
            elemento += A[i][k] * B[k][j]
        C[i].append(elemento)
            
            
        
print("\n Matriz A B: ")
for i in range(n):
    for j in range(p):
        print(C[i][j], end=" ")
    print("")

número de filas de A: 2
número de columnas de A: 2
número de columnas de B: 3

 Matriz A 

Introduce el elemento (0,0) de la matriz A: 1
Introduce el elemento (0,1) de la matriz A: 0
Introduce el elemento (1,0) de la matriz A: 0
Introduce el elemento (1,1) de la matriz A: 1

 Matriz B 

Introduce el elemento (0,0) de la matriz B: -5
Introduce el elemento (0,1) de la matriz B: 4
Introduce el elemento (0,2) de la matriz B: 1
Introduce el elemento (1,0) de la matriz B: 1
Introduce el elemento (1,1) de la matriz B: 0
Introduce el elemento (1,2) de la matriz B: 3

 Matriz A B: 
-5.0 4.0 1.0 
1.0 0.0 3.0 


In [11]:
import numpy as np
n = int(input("Número de filas: "))
m = int(input("Número de columnas: "))

A=np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j]=float(input("Introduce el elemento ({},{}): ".format(i,j)))

print(A)

Número de filas: 2
Número de columnas: 3
Introduce el elemento (0,0)2
Introduce el elemento (0,1)3
Introduce el elemento (0,2)1
Introduce el elemento (1,0)0
Introduce el elemento (1,1)4
Introduce el elemento (1,2)4
[[2. 3. 1.]
 [0. 4. 4.]]


In [13]:
import numpy as np
n = int(input("Número de filas: "))
m = int(input("Número de columnas: "))

A=np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j]=float(input("Introduce el elemento ({},{}): ".format(i,j)))
        
B=np.empty((n,m))

for i in range(n):
    for j in range(m):
        B[i,j]=float(input("Introduce el elemento ({},{}): ".format(i,j)))

C=np.empty((n,m))

for i in range(n):
    for j in range(m):
        C[i,j]=A[i,j]+B[i,j]

print(A+B)

print(C)

Número de filas: 2
Número de columnas: 2
Introduce el elemento (0,0): 0
Introduce el elemento (0,1): 1
Introduce el elemento (1,0): 2
Introduce el elemento (1,1): 4
Introduce el elemento (0,0): 5
Introduce el elemento (0,1): 1
Introduce el elemento (1,0): 0
Introduce el elemento (1,1): 2
[[5. 2.]
 [2. 6.]]
[[5. 2.]
 [2. 6.]]


In [15]:
import numpy as np
n = int(input("Número de filas de A: "))
m = int(input("Número de columnas de A: "))
p = int(input("Número de columnas de B: "))

A=np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j]=float(input("Introduce el elemento ({},{}): ".format(i,j)))
        
B=np.empty((m,p))

for i in range(m):
    for j in range(p):
        B[i,j]=float(input("Introduce el elemento ({},{}): ".format(i,j)))

print(A*B)
print(A.dot(B))



Número de filas de A: 2
Número de columnas de A: 1
Número de columnas de B: 2
Introduce el elemento (0,0): 0
Introduce el elemento (1,0): 1
Introduce el elemento (0,0): 2
Introduce el elemento (0,1): 2
[[0. 0.]
 [2. 2.]]
[[0. 0.]
 [2. 2.]]
