In [24]:
n = int(input("Introduzca el número de caracteres: "))
list_0 = []

for i in range(n):
    char = input("Introduce el caracter: ")
    list_0.append(char)

list_0.reverse()
print(list_0)

    

Introduzca el número de caracteres: 2
Introduce el caracter: a
Introduce el caracter: b
['b', 'a']


In [26]:
str_1 = input("Introduce una frase: ")
str_2 = input("Introduce otra frase de la misma longitud: ")

stra = []
if len(str_1) == len(str_2):
    for i in range(len(str_1)):
        stra.append(str_1[i]+str_2[i])
        print(stra[i], end = "")
else:
    print("no tienen la misma longitud ")
    

Introduce una frase: hola caracola
Introduce otra frase de la misma longitud: adios marieta
haodliao sc amraarcioeltaa

In [15]:
phrase = input("Introduzca una frase: ")
phrase.lower()
str = []

for i in range(len(phrase)):
    if phrase[i]!="a" and phrase[i]!="e" and phrase[i]!="i" and phrase[i]!="o" and phrase[i]!="u" and phrase[i]!= " ":
        str.append(phrase[i])
    else:
        continue
    
print(str)
    

Introduzca una frase: hola como estan
['h', 'l', 'c', 'm', 's', 't', 'n']


In [37]:
str_1 =input("Introduzca una palabra: ")
str_1.lower()

list_0 = []
list_1=[]
for i in range(len(str_1)):
    list_0.append(str_1[i])

list_1 = list_0.copy()
list_1.reverse()

if list_0 == list_1:
    print("La palabra {} es palindromo".format(str_1))
else:
    print("La palabra {} no es palindromo".format(str_1))
        

Introduzca una palabra: acurruca
La palabra acurruca es palindromo


In [43]:
import numpy as np

A=np.empty((3,3))
for i in range(3):
    for j in range(3):
        A[i,j] = int (input("Introduce el elemento ({},{}): ".format(i,j)))
        
for i in range(3):
    for j in range(3):
        if A[i,j ] > A[i,j-1]:
            continue
        else:
            A[i,j] = A[i,j-1]
    print("El máximo elemento de la fila {} es {}".format(i,A[i,j]))

Introduce el elemento (0,0): -5
Introduce el elemento (0,1): 4
Introduce el elemento (0,2): 0
Introduce el elemento (1,0): 0
Introduce el elemento (1,1): -1
Introduce el elemento (1,2): -3
Introduce el elemento (2,0): 4
Introduce el elemento (2,1): 1
Introduce el elemento (2,2): 10
El máximo elemento de la fila 0 es 4.0
El máximo elemento de la fila 1 es 0.0
El máximo elemento de la fila 2 es 10.0


In [106]:
n = int(input("Ingresa el orden de la matriz: "))
A=[[]]

for j in range(n):
    A[0].append(j)

for i in range(1,n):
    A.append([])
    for j in range(0,n):
        A[i].append(A[i-1][j]+n)
        
for i in range(n):
        print(A[i], " ")

    

Ingresa el orden de la matriz: 3
[0, 1, 2]  
[3, 4, 5]  
[6, 7, 8]  


In [146]:
import numpy as np
n=int(input("Introduce elnúmero de filas: "))
m=int(input("Introduce elnúmero de columnas: "))

A=np.empty((n,m))
for i in range(n):
    for j in range(m):
        A[i,j]=float(input("Introduce la entrada ({},{}): ".format(i,j)))
print(A)

c=np.empty((m))
for i in range(m):
    c_i=0
    for j in range(n):
        c_i = c_i + A[j,i] 
    c[i]=c_i

R=np.empty((m))
for j in range(m):
    R[j]=c[0]
    
value = True
for i in range(m):
    if R[i]-c[i] == 0:
        value =value and True
    else:
        value=value and False

if value == True:
    print("El valor de la suma de cada columna es el mismo")
else:
     print("El valor de la suma de cada columna no es el mismo")


            

Introduce elnúmero de filas: 3
Introduce elnúmero de columnas: 2
Introduce la entrada (0,0): 0
Introduce la entrada (0,1): 3
Introduce la entrada (1,0): 2
Introduce la entrada (1,1): 2
Introduce la entrada (2,0): 3
Introduce la entrada (2,1): 0
[[0. 3.]
 [2. 2.]
 [3. 0.]]
El valor de la suma de cada columna es el mismo


In [156]:
import numpy as np
n = int (input("Introduce la dimensión de la matriz: "))

A=np.empty((n,n))
for i in range(n):
    for j in range(n):
        A[i,j]=int(input("Introduce la entrada ({},{}): ".format(i,j)))

Id=np.empty((n,n))
for i in range(n):
    for j in range(n):
        if i != j:
             Id[i,j]=0
        else:
            Id[i,j]=1

if (A-Id== np.zeros((n,n))).all()==True:
    print("Usted introdujo la matriz identidad")
else:
    print("Usted no introdujo la matriz identidad")
   

Introduce la dimensión de la matriz: 3
Introduce la entrada (0,0): 1
Introduce la entrada (0,1): 0
Introduce la entrada (0,2): 0
Introduce la entrada (1,0): 0
Introduce la entrada (1,1): 1
Introduce la entrada (1,2): 0
Introduce la entrada (2,0): 0
Introduce la entrada (2,1): 0
Introduce la entrada (2,2): 1
Usted introdujo la matriz identidad


In [164]:
import numpy as np
n = int (input("Introduce el número de filas de la matriz: "))
m= int (input("Introduce el número de columnas de la matriz: "))

A=np.empty((n,m))
for i in range(n):
    for j in range(m):
        A[i,j]=int(input("Introduce la entrada ({},{}): ".format(i,j)))

B=np.empty((m,n))
for i in range(m):
    for j in range(n):
        B[i,j]=A[j,i]

print("La matriz transpuesta de la matriz\n {} \n  es \n {}".format(A,B))

Introduce el número de filas de la matriz: 3
Introduce el número de columnas de la matriz: 1
Introduce la entrada (0,0): 1
Introduce la entrada (1,0): 2
Introduce la entrada (2,0): 3
La matriz transpuesta de la matriz
 [[1.]
 [2.]
 [3.]] 
  es 
 [[1. 2. 3.]]


In [165]:
import numpy as np
n=int(input("Introduce la dimensión: "))
Id=np.empty((n,n))

for i in range(n):
    for j in range(n):
        if i != j:
             Id[i,j]=0
        else:
            Id[i,j]=1

print(Id)


Introduce la dimensión: 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
